name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Get example (well formed) applications
        run: |
          mkdir applications;
          mkdir maintenance;
          cd applications;
          wget "https://raw.githubusercontent.com/w3f/Grants-Program/master/applications/AdMeta.md";
          cd ../maintenance;
          wget "https://raw.githubusercontent.com/w3f/Grants-Program/master/applications/maintenance/wasm-opt-for-rust.md"
      - name: Test action with normal application
        uses: ./
        with:
          path: applications/AdMeta.md
      - name: Test action with maintenance application
        uses: ./
        with:
          path: maintenance/wasm-opt-for-rust.md