name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Get example (well formed) applications
        run: |
          wget "https://raw.githubusercontent.com/w3f/Grants-Program/master/applications/AdMeta.md";
          wget "https://raw.githubusercontent.com/w3f/Grants-Program/master/maintenance/wasm-opt-for-rust.md"
      - name: Test action with normal application
        uses: ./
        with:
          path: AdMeta.md
      - name: Test action with maintenance application
        uses: ./
        with:
          path: wasm-opt-for-rust.md